// Autocomplete symbol catalogue for the NgpCraft Live Editor.
//
// Each entry describes one public API name the user code is likely to type.
// Kept intentionally concise: one short English sentence for `doc`, with the
// C signature so the docstring panel reads like a header file. Entries map
// 1:1 against js/runtime.js and js/api.js so anything here is something the
// runtime actually implements.
//
// Fields:
//   name      — the identifier as the user will type it
//   kind      — 'function' | 'constant' | 'register' | 'macro' | 'type'
//   signature — C-style prototype or `#define` form (for the doc panel)
//   doc       — one-sentence English description
//
// Order inside the array is not significant; the UI sorts by prefix match.

const NGPC_AUTOCOMPLETE = [
  /* =================== System / lifecycle =================== */
  { name: 'ngpc_init', kind: 'function',
    signature: 'void ngpc_init(void)',
    doc: 'Initialize NGPC hardware: viewport 160x152, scroll+sprite offsets zeroed, LCD inversion cleared, repeat-timer seeded. Call first in main().' },
  { name: 'ngpc_shutdown', kind: 'function',
    signature: 'void ngpc_shutdown(void)',
    doc: 'Halts the program via BIOS. In the emulator throws NGPC_SHUTDOWN so the host loop stops cleanly.' },
  { name: 'ngpc_is_color', kind: 'function',
    signature: 'u8 ngpc_is_color(void)',
    doc: 'Returns 1 on NGPC (color), 0 on mono NGP. Reads BIOS byte 0x6F91.' },
  { name: 'ngpc_get_language', kind: 'function',
    signature: 'u8 ngpc_get_language(void)',
    doc: 'Returns 0 = LANG_ENGLISH, 1 = LANG_JAPANESE. Reads BIOS byte 0x6F87.' },
  { name: 'ngpc_memcpy', kind: 'function',
    signature: 'void ngpc_memcpy(u32 dst, u32 src, u16 len)',
    doc: 'Byte-wise copy len bytes from src to dst in the emulated address space. `memcpy` is aliased to this.' },
  { name: 'ngpc_memset', kind: 'function',
    signature: 'void ngpc_memset(u32 dst, u8 val, u16 len)',
    doc: 'Write val to len bytes starting at dst. `memset` is aliased to this.' },

  /* =================== Timing =================== */
  { name: 'ngpc_vsync', kind: 'function',
    signature: 'void ngpc_vsync(void)',
    doc: 'Wait for VBlank. Transpiles to `yield;` so the 60 Hz host loop advances. Pets the watchdog via the simulated VBI.' },
  { name: 'ngpc_sleep', kind: 'function',
    signature: 'void ngpc_sleep(u16 frames)',
    doc: 'Yield for N frames. Expanded inline to a bounded vsync loop; must be called from main().' },
  { name: 'ngpc_in_vblank', kind: 'function',
    signature: 'u8 ngpc_in_vblank(void)',
    doc: 'Returns non-zero during the simulated VBlank window (HW_STATUS bit 6).' },

  /* =================== Graphics — palette / BG =================== */
  { name: 'ngpc_gfx_set_bg_color', kind: 'function',
    signature: 'void ngpc_gfx_set_bg_color(u16 rgb)',
    doc: 'Set the backdrop color (HW_PAL_BG[0]). Use RGB(r,g,b) to build the value.' },
  { name: 'ngpc_gfx_set_palette', kind: 'function',
    signature: 'void ngpc_gfx_set_palette(u8 plane, u8 pal_id, u16 c0, u16 c1, u16 c2, u16 c3)',
    doc: 'Write 4 colours to plane palette pal_id (0..15). plane = GFX_SCR1, GFX_SCR2 or GFX_SPR.' },
  { name: 'ngpc_gfx_set_color_direct', kind: 'function',
    signature: 'void ngpc_gfx_set_color_direct(u8 plane, u8 pal_id, u8 idx, u16 color)',
    doc: 'Write a single palette slot. Use for one-frame hit-flash without disturbing shadow state.' },
  { name: 'ngpc_gfx_set_outside_color', kind: 'function',
    signature: 'void ngpc_gfx_set_outside_color(u8 pal_idx)',
    doc: 'Choose the BG palette entry (0..7) shown outside the viewport (letterbox bars).' },
  { name: 'RGB', kind: 'macro',
    signature: '#define RGB(r, g, b)',
    doc: 'Build an RGB444 colour word (each channel 0..15). Used by every palette call.' },

  /* =================== Graphics — tilemap =================== */
  { name: 'ngpc_gfx_put_tile', kind: 'function',
    signature: 'void ngpc_gfx_put_tile(u8 plane, u8 x, u8 y, u16 tile, u8 pal)',
    doc: 'Place a tile at (x,y) on a scroll plane. Tile coords are 0..31 (32x32 map).' },
  { name: 'ngpc_gfx_put_tile_ex', kind: 'function',
    signature: 'void ngpc_gfx_put_tile_ex(u8 plane, u8 x, u8 y, u16 tile, u8 pal, u8 hflip, u8 vflip)',
    doc: 'Like put_tile but with per-tile horizontal/vertical flip bits.' },
  { name: 'ngpc_gfx_get_tile', kind: 'function',
    signature: '{tile,pal} ngpc_gfx_get_tile(u8 plane, u8 x, u8 y)',
    doc: 'Read back the tile index + palette at (x,y).' },
  { name: 'ngpc_gfx_clear', kind: 'function',
    signature: 'void ngpc_gfx_clear(u8 plane)',
    doc: 'Zero every map entry of a scroll plane.' },
  { name: 'ngpc_gfx_fill', kind: 'function',
    signature: 'void ngpc_gfx_fill(u8 plane, u16 tile, u8 pal)',
    doc: 'Fill the entire 32x32 tilemap with one (tile,pal) pair.' },
  { name: 'ngpc_gfx_fill_rect', kind: 'function',
    signature: 'void ngpc_gfx_fill_rect(u8 plane, u8 x, u8 y, u8 w, u8 h, u16 tile, u8 pal)',
    doc: 'Fill a W×H tile rect starting at (x,y). Wraps at the 32-tile map edge.' },
  { name: 'ngpc_gfx_set_rect_pal', kind: 'function',
    signature: 'void ngpc_gfx_set_rect_pal(u8 plane, u8 x, u8 y, u8 w, u8 h, u8 pal)',
    doc: 'Repaint palette of a tile rectangle without touching tile indices or flip bits.' },

  /* =================== Graphics — tile data upload =================== */
  { name: 'ngpc_gfx_load_tiles', kind: 'function',
    signature: 'void ngpc_gfx_load_tiles(const u16 *tiles, u16 count)',
    doc: 'Copy u16 tile words into VRAM starting at tile 0. count = num_tiles * 8.' },
  { name: 'ngpc_gfx_load_tiles_at', kind: 'function',
    signature: 'void ngpc_gfx_load_tiles_at(const u16 *tiles, u16 count, u16 tile_offset)',
    doc: 'Copy u16 tile words into VRAM starting at tile_offset (0..511).' },
  { name: 'ngpc_gfx_load_tiles_u8', kind: 'function',
    signature: 'void ngpc_gfx_load_tiles_u8(const u8 *bytes, u16 tile_count)',
    doc: 'Copy raw 16-byte-per-tile data. Avoids any u16 endian confusion.' },
  { name: 'ngpc_gfx_load_tiles_u8_at', kind: 'function',
    signature: 'void ngpc_gfx_load_tiles_u8_at(const u8 *bytes, u16 tile_count, u16 tile_offset)',
    doc: 'Byte variant of load_tiles_at.' },

  /* =================== Graphics — scroll / viewport =================== */
  { name: 'ngpc_gfx_scroll', kind: 'function',
    signature: 'void ngpc_gfx_scroll(u8 plane, u8 x, u8 y)',
    doc: 'Set scroll offset on a plane (HW_SCR1_OFS / HW_SCR2_OFS).' },
  { name: 'ngpc_gfx_scroll_parallax', kind: 'function',
    signature: 'void ngpc_gfx_scroll_parallax(s16 cam_x, s16 cam_y, u8 scr1_shift, u8 scr2_shift)',
    doc: 'Apply right-shift parallax to both planes. Pass 0xFF to freeze a plane at origin.' },
  { name: 'ngpc_gfx_swap_planes', kind: 'function',
    signature: 'void ngpc_gfx_swap_planes(void)',
    doc: 'Toggle HW_SCR_PRIO bit 7 — swaps which scroll plane is in front.' },
  { name: 'ngpc_gfx_set_viewport', kind: 'function',
    signature: 'void ngpc_gfx_set_viewport(u8 x, u8 y, u8 w, u8 h)',
    doc: 'Set the K2GE window (HW_WIN_X/Y/W/H). Max w=160, h=152.' },
  { name: 'ngpc_gfx_sprite_offset', kind: 'function',
    signature: 'void ngpc_gfx_sprite_offset(u8 x, u8 y)',
    doc: 'Shift all sprites globally via HW_SPR_OFS_X/Y. Useful for screen shake.' },
  { name: 'ngpc_gfx_lcd_invert', kind: 'function',
    signature: 'void ngpc_gfx_lcd_invert(u8 enable)',
    doc: 'Toggle negative-display mode (HW_LCD_CTL bit 7).' },
  { name: 'ngpc_gfx_char_over', kind: 'function',
    signature: 'u8 ngpc_gfx_char_over(void)',
    doc: 'Returns 1 if a Character Over occurred this frame (HW_STATUS bit 7).' },

  /* =================== Sprites =================== */
  { name: 'ngpc_sprite_set', kind: 'function',
    signature: 'void ngpc_sprite_set(u8 id, u8 x, u8 y, u16 tile, u8 pal, u8 flags)',
    doc: 'Full sprite write (id 0..63). flags = SPR_FRONT | SPR_HFLIP | SPR_VFLIP | SPR_HCHAIN | SPR_VCHAIN.' },
  { name: 'ngpc_sprite_move', kind: 'function',
    signature: 'void ngpc_sprite_move(u8 id, u8 x, u8 y)',
    doc: 'Reposition an existing sprite without touching tile or palette.' },
  { name: 'ngpc_sprite_hide', kind: 'function',
    signature: 'void ngpc_sprite_hide(u8 id)',
    doc: 'Clear the priority bits of sprite id (makes it invisible).' },
  { name: 'ngpc_sprite_hide_all', kind: 'function',
    signature: 'void ngpc_sprite_hide_all(void)',
    doc: 'Hide every OAM slot in one call.' },
  { name: 'ngpc_sprite_set_flags', kind: 'function',
    signature: 'void ngpc_sprite_set_flags(u8 id, u8 flags)',
    doc: 'Update the flag byte (priority + flips + chain) without moving the sprite.' },
  { name: 'ngpc_sprite_set_tile', kind: 'function',
    signature: 'void ngpc_sprite_set_tile(u8 id, u16 tile)',
    doc: 'Swap the tile index on an existing sprite slot.' },
  { name: 'ngpc_sprite_get_pal', kind: 'function',
    signature: 'u8 ngpc_sprite_get_pal(u8 id)',
    doc: 'Read the palette number assigned to sprite id.' },
  { name: 'ngpc_sprite_frame_begin', kind: 'function',
    signature: 'void ngpc_sprite_frame_begin(void)',
    doc: 'Mark the start of a frame for OAM shadow buffering. No-op in the emulator.' },
  { name: 'ngpc_sprite_frame_end', kind: 'function',
    signature: 'void ngpc_sprite_frame_end(void)',
    doc: 'Mark the end of a frame for OAM shadow buffering. No-op in the emulator.' },

  /* =================== Metasprites =================== */
  { name: 'ngpc_mspr_draw', kind: 'function',
    signature: 'u8 ngpc_mspr_draw(u8 spr_start, s16 x, s16 y, const NgpcMetasprite *def, u8 flags)',
    doc: 'Expand a NgpcMetasprite into multiple hardware sprites at (x,y).' },
  { name: 'ngpc_mspr_hide', kind: 'function',
    signature: 'void ngpc_mspr_hide(u8 spr_start, u8 count)',
    doc: 'Hide count consecutive OAM slots — paired with a previous ngpc_mspr_draw.' },
  { name: 'ngpc_mspr_anim_start', kind: 'function',
    signature: 'void ngpc_mspr_anim_start(MsprAnimator *a, const MsprAnimFrame *anim, u8 count, u8 loop)',
    doc: 'Begin an animation. a is a MsprAnimator state, anim is a frame+duration table.' },
  { name: 'ngpc_mspr_anim_update', kind: 'function',
    signature: 'const NgpcMetasprite * ngpc_mspr_anim_update(MsprAnimator *a)',
    doc: 'Tick one frame of the animation and return the current metasprite to draw.' },
  { name: 'ngpc_mspr_anim_done', kind: 'function',
    signature: 'u8 ngpc_mspr_anim_done(MsprAnimator *a)',
    doc: 'Returns 1 if a non-looping animation has finished.' },

  /* =================== Bitmap =================== */
  { name: 'ngpc_bmp_init', kind: 'function',
    signature: 'void ngpc_bmp_init(u8 plane, u16 tile_offset, u8 pal)',
    doc: 'Wire 380 unique tiles to a scroll plane for 160x152 software pixel drawing.' },
  { name: 'ngpc_bmp_pixel', kind: 'function',
    signature: 'void ngpc_bmp_pixel(u8 x, u8 y, u8 color)',
    doc: 'Set one pixel (color 0..3). Warns if (x,y) is outside the bitmap area.' },
  { name: 'ngpc_bmp_get_pixel', kind: 'function',
    signature: 'u8 ngpc_bmp_get_pixel(u8 x, u8 y)',
    doc: 'Read back a pixel colour (0..3).' },
  { name: 'ngpc_bmp_clear', kind: 'function',
    signature: 'void ngpc_bmp_clear(void)',
    doc: 'Zero every pixel of the bitmap area.' },
  { name: 'ngpc_bmp_line', kind: 'function',
    signature: 'void ngpc_bmp_line(u8 x1, u8 y1, u8 x2, u8 y2, u8 color)',
    doc: 'Draw a Bresenham line between two points.' },
  { name: 'ngpc_bmp_hline', kind: 'function',
    signature: 'void ngpc_bmp_hline(u8 x, u8 y, u8 w, u8 color)',
    doc: 'Horizontal line of width w at (x,y).' },
  { name: 'ngpc_bmp_vline', kind: 'function',
    signature: 'void ngpc_bmp_vline(u8 x, u8 y, u8 h, u8 color)',
    doc: 'Vertical line of height h at (x,y).' },
  { name: 'ngpc_bmp_rect', kind: 'function',
    signature: 'void ngpc_bmp_rect(u8 x, u8 y, u8 w, u8 h, u8 color)',
    doc: 'Hollow rectangle outline.' },
  { name: 'ngpc_bmp_fill_rect', kind: 'function',
    signature: 'void ngpc_bmp_fill_rect(u8 x, u8 y, u8 w, u8 h, u8 color)',
    doc: 'Filled rectangle.' },

  /* =================== Text =================== */
  { name: 'ngpc_load_sysfont', kind: 'function',
    signature: 'void ngpc_load_sysfont(void)',
    doc: 'Load the 96 printable ASCII glyphs into VRAM at tile index = ASCII code.' },
  { name: 'ngpc_text_print', kind: 'function',
    signature: 'void ngpc_text_print(u8 plane, u8 pal, u8 x, u8 y, const char *s)',
    doc: 'Draw a string on a scroll plane starting at tile (x,y). Sysfont must be loaded.' },
  { name: 'ngpc_text_print_dec', kind: 'function',
    signature: 'void ngpc_text_print_dec(u8 plane, u8 pal, u8 x, u8 y, u16 value, u8 digits)',
    doc: 'Zero-padded decimal number, up to 5 digits.' },
  { name: 'ngpc_text_print_hex', kind: 'function',
    signature: 'void ngpc_text_print_hex(u8 plane, u8 pal, u8 x, u8 y, u16 value, u8 digits)',
    doc: 'Hex number (uppercase A-F), up to 4 digits.' },
  { name: 'ngpc_text_print_num', kind: 'function',
    signature: 'void ngpc_text_print_num(u8 plane, u8 pal, u8 x, u8 y, u16 value, u8 digits)',
    doc: 'Space-padded decimal (leading zeros become spaces).' },
  { name: 'ngpc_text_print_hex32', kind: 'function',
    signature: 'void ngpc_text_print_hex32(u8 plane, u8 pal, u8 x, u8 y, u32 value)',
    doc: '8-digit hex (high word then low word).' },
  { name: 'ngpc_text_tile_screen', kind: 'function',
    signature: 'void ngpc_text_tile_screen(u8 plane, u8 pal, const u8 *map)',
    doc: 'Fill the visible 20x19 region of a plane from a flat tile-index array.' },

  /* =================== Input =================== */
  { name: 'ngpc_input_update', kind: 'function',
    signature: 'void ngpc_input_update(void)',
    doc: 'Sample HW_JOYPAD and refresh ngpc_pad_held/_pressed/_released/_repeat. Call each frame after vsync.' },
  { name: 'ngpc_input_set_repeat', kind: 'function',
    signature: 'void ngpc_input_set_repeat(u8 delay, u8 rate)',
    doc: 'Configure auto-repeat delay and rate (frames).' },
  { name: 'ngpc_pad_held', kind: 'register',
    signature: 'extern u8 ngpc_pad_held',
    doc: 'Bitmask of buttons currently held. Test with PAD_UP, PAD_A etc.' },
  { name: 'ngpc_pad_pressed', kind: 'register',
    signature: 'extern u8 ngpc_pad_pressed',
    doc: 'Bitmask of buttons newly pressed this frame (edge detected).' },
  { name: 'ngpc_pad_released', kind: 'register',
    signature: 'extern u8 ngpc_pad_released',
    doc: 'Bitmask of buttons released this frame.' },
  { name: 'ngpc_pad_repeat', kind: 'register',
    signature: 'extern u8 ngpc_pad_repeat',
    doc: 'Bitmask of buttons firing via the auto-repeat timer.' },
  { name: 'g_vb_counter', kind: 'register',
    signature: 'extern volatile u8 g_vb_counter',
    doc: 'Free-running frame counter incremented by the VBI at 60 Hz.' },

  /* =================== Math =================== */
  { name: 'ngpc_sin', kind: 'function',
    signature: 's8 ngpc_sin(u8 angle)',
    doc: 'Signed sine of angle (0..255 maps to 0..2π). Returns -127..127.' },
  { name: 'ngpc_cos', kind: 'function',
    signature: 's8 ngpc_cos(u8 angle)',
    doc: 'Signed cosine of angle. Range -127..127.' },
  { name: 'ngpc_random', kind: 'function',
    signature: 'u16 ngpc_random(u16 max)',
    doc: 'LCG-based pseudo-random in [0, max).' },
  { name: 'ngpc_rng_seed', kind: 'function',
    signature: 'void ngpc_rng_seed(u32 seed)',
    doc: 'Reseed the LCG random number generator.' },
  { name: 'ngpc_qrandom', kind: 'function',
    signature: 'u8 ngpc_qrandom(void)',
    doc: 'Fisher-Yates shuffled 256-entry quick random. Faster than ngpc_random.' },
  { name: 'ngpc_qrandom_init', kind: 'function',
    signature: 'void ngpc_qrandom_init(void)',
    doc: 'Initialise / reshuffle the quick-random table.' },
  { name: 'ngpc_mul32', kind: 'function',
    signature: 's32 ngpc_mul32(s32 a, s32 b)',
    doc: '32-bit signed multiply (uses Math.imul in the emulator).' },

  /* =================== Palette FX =================== */
  { name: 'ngpc_palfx_fade', kind: 'function',
    signature: 'u8 ngpc_palfx_fade(u8 plane, u8 pal_id, const u16 *target, u8 speed)',
    doc: 'Fade 4 palette entries toward target over 15 steps. Returns the slot index or 0xFF if full.' },
  { name: 'ngpc_palfx_fade_to_black', kind: 'function',
    signature: 'u8 ngpc_palfx_fade_to_black(u8 plane, u8 pal_id, u8 speed)',
    doc: 'Convenience wrapper for a fade-to-black.' },
  { name: 'ngpc_palfx_fade_to_white', kind: 'function',
    signature: 'u8 ngpc_palfx_fade_to_white(u8 plane, u8 pal_id, u8 speed)',
    doc: 'Convenience wrapper for a fade-to-white.' },
  { name: 'ngpc_palfx_cycle', kind: 'function',
    signature: 'u8 ngpc_palfx_cycle(u8 plane, u8 pal_id, u8 speed)',
    doc: 'Rotate palette entries 1→2→3 every `speed` frames (entry 0 stays transparent).' },
  { name: 'ngpc_palfx_flash', kind: 'function',
    signature: 'u8 ngpc_palfx_flash(u8 plane, u8 pal_id, u16 color, u8 duration)',
    doc: 'Flash a palette to one colour for N frames, then restore.' },
  { name: 'ngpc_palfx_update', kind: 'function',
    signature: 'void ngpc_palfx_update(void)',
    doc: 'Advance all active fade/cycle/flash slots. Call once per frame.' },
  { name: 'ngpc_palfx_active', kind: 'function',
    signature: 'u8 ngpc_palfx_active(u8 slot)',
    doc: 'Returns 1 if the slot is still running.' },
  { name: 'ngpc_palfx_stop', kind: 'function',
    signature: 'void ngpc_palfx_stop(u8 slot)',
    doc: 'Stop a specific slot and restore the original palette.' },
  { name: 'ngpc_palfx_stop_all', kind: 'function',
    signature: 'void ngpc_palfx_stop_all(void)',
    doc: 'Stop every palette FX slot.' },

  /* =================== VRAM queue =================== */
  { name: 'ngpc_vramq_init', kind: 'function',
    signature: 'void ngpc_vramq_init(void)',
    doc: 'Reset the VRAM queue state. Call once during boot.' },
  { name: 'ngpc_vramq_copy', kind: 'function',
    signature: 'u8 ngpc_vramq_copy(u16 *dst, const u16 *src, u16 len_words)',
    doc: 'Queue a u16 copy into VRAM. Applies immediately in the emulator. Returns 1 on success.' },
  { name: 'ngpc_vramq_fill', kind: 'function',
    signature: 'u8 ngpc_vramq_fill(u16 *dst, u16 value, u16 len_words)',
    doc: 'Queue a u16 fill. Returns 1 on success.' },
  { name: 'ngpc_vramq_flush', kind: 'function',
    signature: 'void ngpc_vramq_flush(void)',
    doc: 'Drain the queue. No-op in the emulator (copy/fill are immediate).' },
  { name: 'ngpc_vramq_clear', kind: 'function',
    signature: 'void ngpc_vramq_clear(void)',
    doc: 'Discard any queued commands without applying them.' },
  { name: 'ngpc_vramq_pending', kind: 'function',
    signature: 'u8 ngpc_vramq_pending(void)',
    doc: 'Count of commands waiting to flush (always 0 in the emulator).' },
  { name: 'ngpc_vramq_dropped', kind: 'function',
    signature: 'u8 ngpc_vramq_dropped(void)',
    doc: 'Count of commands rejected for invalid destinations.' },
  { name: 'ngpc_vramq_clear_dropped', kind: 'function',
    signature: 'void ngpc_vramq_clear_dropped(void)',
    doc: 'Zero the dropped counter.' },

  /* =================== Audio stubs =================== */
  { name: 'Sounds_Init', kind: 'function',
    signature: 'void Sounds_Init(void)',
    doc: 'Initialise the sound driver. Stub in the emulator — logs only.' },
  { name: 'Sounds_Update', kind: 'function',
    signature: 'void Sounds_Update(void)',
    doc: 'Per-frame audio tick. Stub.' },
  { name: 'Sfx_Play', kind: 'function',
    signature: 'void Sfx_Play(u8 id)',
    doc: 'Trigger a named SFX. Logs `[sfx] play id=N` in the emulator.' },
  { name: 'Sfx_PlayToneCh', kind: 'function',
    signature: 'void Sfx_PlayToneCh(u8 ch, u16 divider, u8 attn, u8 frames)',
    doc: 'Play a raw tone. Logs the arguments in the emulator.' },
  { name: 'Sfx_PlayNoise', kind: 'function',
    signature: 'void Sfx_PlayNoise(u8 noise_val, u8 attn, u8 frames)',
    doc: 'Play a noise burst. Logs the arguments in the emulator.' },
  { name: 'Sfx_Stop', kind: 'function',
    signature: 'void Sfx_Stop(void)',
    doc: 'Silence all SFX channels.' },
  { name: 'Bgm_Start', kind: 'function',
    signature: 'void Bgm_Start(const u8 *stream)',
    doc: 'Begin playing a BGM data stream. Logs in the emulator.' },
  { name: 'Bgm_Stop', kind: 'function',
    signature: 'void Bgm_Stop(void)',
    doc: 'Stop the current BGM.' },
  { name: 'Bgm_FadeOut', kind: 'function',
    signature: 'void Bgm_FadeOut(u8 speed)',
    doc: 'Fade BGM volume toward silence at `speed` frames/step.' },

  /* =================== Debug / log =================== */
  { name: 'ngpc_log_hex', kind: 'function',
    signature: 'void ngpc_log_hex(const char *label, u16 value)',
    doc: 'Log "label  hex". Visible in the editor log pane.' },
  { name: 'ngpc_log_str', kind: 'function',
    signature: 'void ngpc_log_str(const char *label, const char *str)',
    doc: 'Log "label  str".' },
  { name: 'NGPC_ASSERT', kind: 'macro',
    signature: '#define NGPC_ASSERT(cond)',
    doc: 'Abort with a runtime error if cond is false.' },
  { name: 'NGPC_LOG_HEX', kind: 'macro',
    signature: '#define NGPC_LOG_HEX(label, value)',
    doc: 'Shorthand for ngpc_log_hex.' },

  /* =================== Constants: planes, flags, pad =================== */
  { name: 'GFX_SCR1', kind: 'constant', signature: '#define GFX_SCR1 0',
    doc: 'Front scroll plane identifier.' },
  { name: 'GFX_SCR2', kind: 'constant', signature: '#define GFX_SCR2 1',
    doc: 'Back scroll plane identifier.' },
  { name: 'GFX_SPR',  kind: 'constant', signature: '#define GFX_SPR 2',
    doc: 'Sprite plane identifier (for palette calls).' },

  { name: 'SPR_FRONT',  kind: 'constant', signature: '#define SPR_FRONT 0x18',
    doc: 'Sprite priority bits = 11 (in front of both planes).' },
  { name: 'SPR_BACK',   kind: 'constant', signature: '#define SPR_BACK 0x08',
    doc: 'Sprite priority bits = 01 (behind both planes).' },
  { name: 'SPR_MID',    kind: 'constant', signature: '#define SPR_MID 0x10',
    doc: 'Sprite priority bits = 10 (between planes).' },
  { name: 'SPR_HFLIP',  kind: 'constant', signature: '#define SPR_HFLIP 0x80',
    doc: 'Horizontal flip flag on the sprite control byte.' },
  { name: 'SPR_VFLIP',  kind: 'constant', signature: '#define SPR_VFLIP 0x40',
    doc: 'Vertical flip flag.' },
  { name: 'SPR_HCHAIN', kind: 'constant', signature: '#define SPR_HCHAIN 0x04',
    doc: 'H-chain: this slot absorbs the next slot at +8,0 with tile+1.' },
  { name: 'SPR_VCHAIN', kind: 'constant', signature: '#define SPR_VCHAIN 0x02',
    doc: 'V-chain: this slot absorbs a slot at 0,+8 with tile+2.' },

  { name: 'PAD_UP',     kind: 'constant', signature: '#define PAD_UP 0x01',    doc: 'Joypad UP bit.' },
  { name: 'PAD_DOWN',   kind: 'constant', signature: '#define PAD_DOWN 0x02',  doc: 'Joypad DOWN bit.' },
  { name: 'PAD_LEFT',   kind: 'constant', signature: '#define PAD_LEFT 0x04',  doc: 'Joypad LEFT bit.' },
  { name: 'PAD_RIGHT',  kind: 'constant', signature: '#define PAD_RIGHT 0x08', doc: 'Joypad RIGHT bit.' },
  { name: 'PAD_A',      kind: 'constant', signature: '#define PAD_A 0x10',     doc: 'A button bit.' },
  { name: 'PAD_B',      kind: 'constant', signature: '#define PAD_B 0x20',     doc: 'B button bit.' },
  { name: 'PAD_OPTION', kind: 'constant', signature: '#define PAD_OPTION 0x40',doc: 'OPTION button bit.' },
  { name: 'PAD_POWER',  kind: 'constant', signature: '#define PAD_POWER 0x80', doc: 'POWER bit (long press shuts down).' },

  /* =================== HW register macros =================== */
  { name: 'HW_LCD_CTL',    kind: 'register', signature: 'HW_LCD_CTL  /* u8 @ 0x8012 */',
    doc: 'LCD control: bit 7 = inversion, bits 2-0 = outside-window colour index.' },
  { name: 'HW_BG_CTL',     kind: 'register', signature: 'HW_BG_CTL   /* u8 @ 0x8118 */',
    doc: 'Background enable (bit 7) + BG palette index bits 2-0.' },
  { name: 'HW_STATUS',     kind: 'register', signature: 'HW_STATUS   /* u8 @ 0x8010 read-only */',
    doc: 'Bit 7 = Character Over, bit 6 = V-Blanking.' },
  { name: 'HW_SCR1_OFS_X', kind: 'register', signature: 'HW_SCR1_OFS_X /* u8 @ 0x8032 */',
    doc: 'SCR1 horizontal scroll offset.' },
  { name: 'HW_SCR1_OFS_Y', kind: 'register', signature: 'HW_SCR1_OFS_Y /* u8 @ 0x8033 */',
    doc: 'SCR1 vertical scroll offset.' },
  { name: 'HW_SCR2_OFS_X', kind: 'register', signature: 'HW_SCR2_OFS_X /* u8 @ 0x8034 */',
    doc: 'SCR2 horizontal scroll offset.' },
  { name: 'HW_SCR2_OFS_Y', kind: 'register', signature: 'HW_SCR2_OFS_Y /* u8 @ 0x8035 */',
    doc: 'SCR2 vertical scroll offset.' },
  { name: 'HW_SCR_PRIO',   kind: 'register', signature: 'HW_SCR_PRIO  /* u8 @ 0x8030 */',
    doc: 'Plane priority: bit 7 = 0 → SCR1 front, 1 → SCR2 front.' },
  { name: 'HW_WATCHDOG',   kind: 'register', signature: 'HW_WATCHDOG  /* u8 @ 0x006F */',
    doc: 'Pet the watchdog by writing 0x4E. The VBI handles this for you.' },
  { name: 'HW_JOYPAD',     kind: 'register', signature: 'HW_JOYPAD    /* u8 @ 0x6F82 */',
    doc: 'Raw joypad bitmask. Normally read via ngpc_input_update.' },

  { name: 'HW_PAL_SCR1',   kind: 'register', signature: 'HW_PAL_SCR1[i]  /* u16 @ 0x8280 */',
    doc: 'SCR1 palette RAM (16 palettes × 4 colours, u16 access only).' },
  { name: 'HW_PAL_SCR2',   kind: 'register', signature: 'HW_PAL_SCR2[i]  /* u16 @ 0x8300 */',
    doc: 'SCR2 palette RAM.' },
  { name: 'HW_PAL_SPR',    kind: 'register', signature: 'HW_PAL_SPR[i]   /* u16 @ 0x8200 */',
    doc: 'Sprite palette RAM.' },
  { name: 'HW_PAL_BG',     kind: 'register', signature: 'HW_PAL_BG[i]    /* u16 @ 0x83E0 */',
    doc: 'Background palette (8 entries).' },
  { name: 'HW_SCR1_MAP',   kind: 'register', signature: 'HW_SCR1_MAP[i]  /* u16 @ 0x9000 */',
    doc: 'SCR1 tilemap (32×32 u16 entries).' },
  { name: 'HW_SCR2_MAP',   kind: 'register', signature: 'HW_SCR2_MAP[i]  /* u16 @ 0x9800 */',
    doc: 'SCR2 tilemap.' },
  { name: 'HW_SPR_DATA',   kind: 'register', signature: 'HW_SPR_DATA[i]  /* u8 @ 0x8800 */',
    doc: 'OAM (64 sprites × 4 bytes).' },
  { name: 'HW_SPR_PAL',    kind: 'register', signature: 'HW_SPR_PAL[i]   /* u8 @ 0x8C00 */',
    doc: 'Per-sprite palette indices (64 bytes).' },
  { name: 'HW_TILE_DATA',  kind: 'register', signature: 'HW_TILE_DATA[i] /* u16 @ 0xA000 */',
    doc: 'Character RAM (512 tiles × 16 bytes).' },

  /* =================== Types =================== */
  { name: 'u8',   kind: 'type', signature: 'typedef unsigned char u8',
    doc: '8-bit unsigned integer.' },
  { name: 'u16',  kind: 'type', signature: 'typedef unsigned short u16',
    doc: '16-bit unsigned integer.' },
  { name: 'u32',  kind: 'type', signature: 'typedef unsigned long u32',
    doc: '32-bit unsigned integer.' },
  { name: 's8',   kind: 'type', signature: 'typedef signed char s8',
    doc: '8-bit signed integer.' },
  { name: 's16',  kind: 'type', signature: 'typedef signed short s16',
    doc: '16-bit signed integer.' },
  { name: 's32',  kind: 'type', signature: 'typedef signed long s32',
    doc: '32-bit signed integer.' },
  { name: 'NgpcMetasprite', kind: 'type',
    signature: 'typedef struct { u8 count; u8 width; u8 height; MsprPart parts[N]; } NgpcMetasprite',
    doc: 'Metasprite definition emitted by ngpc_sprite_export.py.' },
  { name: 'MsprAnimator', kind: 'type',
    signature: 'typedef struct { const MsprAnimFrame *anim; u8 frame_count; u8 current; u8 timer; u8 loop; } MsprAnimator',
    doc: 'Animation state machine used with ngpc_mspr_anim_*.' },
];
