#!/usr/bin/env python3
"""
Regenerate js/project_data.js by inlining the contents of template/* into a
single JS object literal. Run whenever the template/ files change.

Why inline (vs. fetch()): keeps everything synchronous so the live editor boots
in one tick. Also makes headless-browser screenshot testing reliable.
"""
from pathlib import Path
import json

ROOT = Path(__file__).parent
TEMPLATE_DIR = ROOT / 'template'
MANIFEST = [
    ('src/main.c',              {'editable': True,  'entry': True}),
    ('src/core/ngpc_types.h',   {'editable': False}),
    ('src/core/ngpc_sys.h',     {'editable': False}),
    ('src/core/ngpc_input.h',   {'editable': False}),
    ('src/gfx/ngpc_gfx.h',      {'editable': False}),
    ('src/gfx/ngpc_text.h',     {'editable': False}),
]

def main():
    lines = [
        '// AUTO-GENERATED by sync_template.py — do not edit by hand.',
        '// Regenerate after modifying any file under template/.',
        '',
        'const NGPC_PROJECT_DATA = [',
    ]
    for path, meta in MANIFEST:
        content = (TEMPLATE_DIR / path).read_text()
        meta_json = ', '.join(f'{k}: {json.dumps(v)}' for k, v in meta.items())
        lines.append(f'  {{')
        lines.append(f'    path: {json.dumps(path)},')
        lines.append(f'    {meta_json},')
        lines.append(f'    content: {json.dumps(content)},')
        lines.append(f'  }},')
    lines.append('];')
    lines.append('')

    out = ROOT / 'js' / 'project_data.js'
    out.write_text('\n'.join(lines))
    print(f'Wrote {out} ({len(MANIFEST)} files)')

if __name__ == '__main__':
    main()
