#!/usr/bin/env python3
"""
Bake an 8x8 ASCII font into js/font_data.js.

Uses PIL to render each printable ASCII glyph at 8x8 pixels with a monospace
TTF, thresholds to 1bpp, and emits a JS module containing the packed NGPC
2bpp tile bytes. Re-run whenever the chosen font or rendering params change.

Why not Canvas: the browser's 8px text rendering is inconsistent across
machines and barely legible. Baking a deterministic font at build time gives
a predictable, legible result for every user.
"""
from pathlib import Path
from PIL import Image, ImageFont, ImageDraw

ROOT = Path(__file__).parent
OUT_PATH = ROOT / 'js' / 'font_data.js'

FONT_PATH = None                # None = PIL built-in pixel bitmap font
# PIL's default font is a 7x11 pixel-exact bitmap — it ships with Pillow and
# is specifically designed to render cleanly at small sizes. Rendering into
# an 8x8 tile with a tiny vertical offset fits capital letters/digits
# perfectly and keeps lowercase legible (descenders may clip a single row).
TILE_SIZE = 8
SUPERSAMPLE = 1                 # no oversampling: font is already pixel-exact
RENDER_SIZE = TILE_SIZE
RENDER_Y_OFFSET = -2            # lift so top of caps lands on row 0
DOWNSAMPLE_THRESHOLD = 96       # mid-grey threshold

ASCII_MIN = 0x20
ASCII_MAX = 0x7F

def render_glyph(font, ch):
    big = Image.new('L', (RENDER_SIZE, RENDER_SIZE), 0)
    d = ImageDraw.Draw(big)
    d.text((0, RENDER_Y_OFFSET), ch, 255, font=font)

    # Downsample SUPERSAMPLE x SUPERSAMPLE block -> 1 pixel by averaging.
    area = SUPERSAMPLE * SUPERSAMPLE
    pixels = []
    for y in range(TILE_SIZE):
        for x in range(TILE_SIZE):
            s = 0
            for dy in range(SUPERSAMPLE):
                for dx in range(SUPERSAMPLE):
                    s += big.getpixel((x * SUPERSAMPLE + dx, y * SUPERSAMPLE + dy))
            avg = s / area
            pixels.append(avg > DOWNSAMPLE_THRESHOLD)
    return pixels

def to_ngpc_tile(pixels):
    """
    Convert a flat list of 64 booleans (row-major) to a 16-byte NGPC 2bpp
    packed tile (K2GETechRef §4-3-5-1):
      row byte 0 (even) = dots 4..7, two bits each
      row byte 1 (odd)  = dots 0..3, two bits each
    We use color index 1 for lit pixels, 0 for background.
    """
    out = bytearray(16)
    for y in range(8):
        b0 = 0
        b1 = 0
        for x in range(8):
            lit = 1 if pixels[y * 8 + x] else 0
            dot_in_byte = x & 3
            shift = (3 - dot_in_byte) * 2
            if x < 4:
                b1 |= lit << shift
            else:
                b0 |= lit << shift
        out[y * 2] = b0
        out[y * 2 + 1] = b1
    return out

def main():
    font = (ImageFont.truetype(FONT_PATH, RENDER_SIZE)
            if FONT_PATH else ImageFont.load_default())
    glyphs = {}
    for cp in range(ASCII_MIN, ASCII_MAX + 1):
        ch = chr(cp)
        if cp == ASCII_MIN:
            # space is always blank
            glyphs[cp] = bytes(16)
            continue
        pixels = render_glyph(font, ch)
        glyphs[cp] = bytes(to_ngpc_tile(pixels))

    # Emit as a compact hex map keyed by code point.
    lines = [
        '// AUTO-GENERATED by sync_font.py — do not edit by hand.',
        f'// Source: {FONT_PATH} @ {RENDER_SIZE}px 2x-downsampled, threshold={DOWNSAMPLE_THRESHOLD}, y_offset={RENDER_Y_OFFSET}',
        f'// Range: 0x{ASCII_MIN:02X}..0x{ASCII_MAX:02X} ({ASCII_MAX - ASCII_MIN + 1} glyphs).',
        '',
        'const NGPC_FONT_DATA = {',
    ]
    for cp, tile in glyphs.items():
        hex_bytes = ''.join(f'{b:02x}' for b in tile)
        lines.append(f'  0x{cp:02X}: "{hex_bytes}",')
    lines.append('};')
    lines.append('')

    OUT_PATH.write_text('\n'.join(lines))
    print(f'Wrote {OUT_PATH} ({len(glyphs)} glyphs, {len(glyphs)*16} bytes of tile data)')

if __name__ == '__main__':
    main()
